config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get "/about" => "home#about"
  resources :items
  resources :users, :only => [:index, :show, :edit, :update, :destroy]
  post "selects" => "select#create"
  get "selects/:id" => "select#show"
  get "selects" => "select#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :selects, dependent: :destroy
	attachment :image
end

app/models/select.rb
class Select < ApplicationRecord
  belongs_to :user
  belongs_to :item
  # params[:search]がfに代入される。
  def self.search(search)
      if search
      	# selectに紐づいたItemからfを見つけ出す。
        Item.find_by(['name LIKE ?', "%#{search}%"]).selects
      else
        Select.all
      end
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :zip_code, presence:true
  validates :home_address, presence:true

  has_one :select, dependent: :destroy

  def self.search(search)
      if search
        User.where(['home_address LIKE ?', "%#{search}%"])
      else
        User.all
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		root_path
	end

	def after_sign_out_path_for(resource)
		root_path
	end

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:zip_code, :home_address])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  	if current_user
  		if current_user.admin == true
			  redirect_to selects_path
  		elsif current_user.select.blank?
  			redirect_to items_path
  		else
  			redirect_to user_path(current_user)
  		end
  	end
  end

  def about
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!
  before_action :admin_check, only:[:new, :show, :edit, :update, :destroy]

  def new
  	@item = Item.new
  end

  def index
  	@items = Item.all
  end

  def create
  	item = Item.new(item_params)
  	if item.save
      flash[:notice] = "商品を掲載いたしました。"
    end
  	redirect_to item_path(item.id)
  end

  def show
  	@item = Item.find(params[:id])
  end

  def edit
  	@item = Item.find(params[:id])
  end

  def update
  	item = Item.find(params[:id])
  	if item.update(item_params)
      flash[:notice] = "商品を更新しました。"
    end
  	redirect_to items_path
  end

  def destroy
  	item = Item.find(params[:id])
  	if item.destroy
      flash[:notice] = "商品を削除いたしました。"
  	redirect_to items_path
    end
  end

  def admin_check
  	if current_user.admin == false
  		redirect_to items_path
  	end
  end

  private

  def item_params
  	params.require(:item).permit(:name, :caption, :image)
  end

end

app/controllers/select_controller.rb
class SelectController < ApplicationController
	before_action :authenticate_user!
    before_action :admin_check, only:[:index]


    def index
        # .searchはモデルで定義しているメソッドを呼び出す。
        @selects = Select.search(params[:search]).page(params[:page]).reverse_order
    end

    def show
        # userが商品選択後に、遷移される
        # 且つ、表示されている内容は、一番最後に選択したものにしたい。
        @user = User.find(current_user.id)
        @select = Select.find(params[:id])
    end

	def create
    # params[:select]で送られてきた、item_idと0.1で1のitem_idとuser_idを保存
    params[:select].each do |di1,di2|
      if di2 == "1" && di1 != nil
        if current_user.select.present?
            @select = Select.find_by(user_id: current_user.id)
            @select.item_id = di1
            @select.update(select_params)
        else
            @select = Select.new(select_params)
            @select.item_id = di1
            @select.user_id = current_user.id
            @select.save
        end
        redirect_to "/selects/#{@select.id}"
    else
        flash[:notice] = "※商品を選択してください"
        redirect_to items_path
      end
    end
	end

    def admin_check
        if current_user.admin == false
            redirect_to items_path
        end
    end


    private

	def select_params
		params.require(:select).permit(:user_id, :item_id, :check_box)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :admin_check, only:[:index]

  def index
  	@users = User.search(params[:search]).page(params[:page]).reverse_order
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      flash[:notice] = "お客様情報を更新しました。"
    end
    redirect_to user_path(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    if user.destroy
      flash[:notice] = "退会いたしました。ご利用いただきありがとうございました。"
    redirect_to root_path
    end
  end

  def admin_check
  	if current_user.admin == false
  		redirect_to items_path
  	end
  end


  private

	def select_params
		params.require(:select).permit(:user_id, :item_id, :check_box)
	end

  def user_params
    params.require(:user).permit(:zip_code, :home_address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/select_helper.rb
module SelectHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="main-about">
	<div class="container-fluid">
		<div class="row">
			<h1 style="line-height: 5em">- Service -</h1>
			<p class="about-text-1" style="line-height: 2em">こちらは無償で毎月Paper（紙）の商品がもらえるサービスです。</p>
			<p class="about-text-2">毎月商品を１つ選ぶことができます。</p>
			<p class="about-text-3">Paper（紙）の商品は多種多様</p>
			<p class="about-text-4">トイレットペーパーや、模造紙、紙袋まで</p>
			<p class="about-text-5">多く取り揃えています。</p>
			<p class="about-text-6">すべて再生紙を利用しているので</p>
			<p class="about-text-7">環境に優しい製品をお届けしています。</p>
		</div>
	</div>
</div>

<div class="main-about">
	<div class="container-fluid">
		<div class="row">
			<h1 style="line-height: 5em">- About Us -</h1>
			<div class="col-md-4">
				<p class="AboutUs-caption">環境保護活動</p>
				<img src="">
				<p style="line-height: 2em">Paperは地球を守りたい。
				<br>Paperは単に自らの節約に努めるだけでなく、
				<br>地球環境の限界をふまえた上で
				<br>社会や人々の夢の実現に貢献することが、
				<br>地球市民としての使命であると考えます。</p>
			</div>
			<div class="col-md-4">
				<p class="AboutUs-caption">途上国への教育支援</p>
				<img src="">
				<p style="line-height: 2em">発展途上国の子どもたちが教育を受ける
				<br>環境作りのために、金銭的な支援だけでなく、
				<br>村との「共存・共栄」を心がけて
				<br>学校建設の支援を行っています。
				<br>Paperは子どもたちへの教育を通じ、
				<br>将来的に地域の発展・向上を目指しています。</p>
			</div>
			<div class="col-md-4">
				<p class="AboutUs-caption">書道普及の活動</p>
				<img src="">
				<p style="line-height: 2em">「Paper（かみ）への感謝の気持ち」
				<br>「正しい美しい愛の習字」を
				<br>次の世代へ伝承する書道教育
				<br>並びに書道文化の振興、国際交流を促進する
				<br>日本文化の発展を目的として活動しています。</p>
			</div>
		</div>
	</div>
</div>

<div class="main-about">
	<div class="container-fluid">
		<div class="row">
			<h1 style="line-height: 5em">- Company -</h1>
			<div class="col-md-2"></div>
			<div class="col-md-8">
				<table>
				  <tr>
				    <th>会社名</th>
				    <td>Paper株式会社</td>
				  </tr>
				  <tr>
				    <th>創業</th>
				    <td>1940年</td>
				  </tr>
				  <tr>
				    <th>資本金</th>
				    <td>300,0000円</td>
				  </tr>
				  <tr>
				    <th>従業員数</th>
				    <td>500人</td>
				  </tr>
				  <tr>
				    <th>電話番号</th>
				    <td>0120-828-828</td>
				  </tr>
				  <tr>
				    <th>事業内容</th>
				    <td>紙製品の製造・販売　/ 教育支援事業　/ 広告代理事業</td>
				  </tr>
				</table>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
</div>

app/views/home/top.html.erb
<div class="main-top">
  <div class="container-fluid">
    <div class="row">
      <h1 style="line-height: 5em">- Paperの世界へようこそ -</h1>
      <p class="top-text-1" style="line-height: 2em" >Paper（紙）とは、字・絵を書いたり、物を包んだりするのに使うモノ。</p>
        <p class="top-text-2">ある人は、好きな人に思いを伝える為に使い、</p>
        <p class="top-text-3">ある人は、人生をかけた、大切な書類を包むのに使う</p>
        <p class="top-text-4">また、ある人は、涙を拭くために使うかもしれない。</p>
        <p class="top-text-5">意外と、必要とされるPaper</p>
        <p class="top-text-6">ペーパーレスといわれるこの時代</p>
        <p class="top-text-7">Paperを無料で差し上げます。</p>
        <p class="top-text-8">ようこそ、無料のかみ（紙）のサービスへ</p>
          <div class="sign_button sign_up_button">
            新規登録
          </div>
          <div class="sign_button sign_in_button">
            ログイン
          </div>
      <div class="sign_modal_wrapper"></div>
        <div class="sign_modal">
          <span class="fa_wrapper"><%= fa_icon "times" %></span>
          <div class="sign_up_modal sign_modal_content">
            <h2>新規会員登録</h2>
            <form class="new_user" action ="/users" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="0vopqXSAxej0lk4KKOWG+YUcG2s5X+btIeQBKegvkob1KNqBEYUcJjZXNJ9bYJDpL+8AncJ0uHNFA4luEVFTAg==">
              <div class="field">
                <label for="user_email">メールアドレス</label><br>
                <input autofocus="autofocus" autocomplete="email" type="email" value="" name="user[email]">
              </div>

              <div class="field">
                <label for="user_zip_code">郵便番号</label><br>
                <input autofocus="autofocus" autocomplete="zip_code" type="zip_code" value="" name="user[zip_code]">
              </div>

              <div class="field">
                <label for="user_home_address">住所</label><br>
                <input autofocus="autofocus" autocomplete="home_address" type="home_address" value="" name="user[home_address]">
              </div>

              <div class="field">
                <label for="user_password">パスワード</label>
                <br>
                <em class="password_confirm">(6桁以上で設定してください)</em>
                <br>
                <input autocomplete="new-password" type="password" name="user[password]" aria-autocomplete="list">
              </div>

              <div class="field">
                <label for="user_password_confirmation">確認用パスワード</label><br>
                <input autocomplete="new-password" type="password" name="user[password_confirmation]">
              </div>

              <div class="actions">
                <input type="submit" name="commit" value="登録" data-disable-with="登録" class="btn btn-default">
              </div>
            </form>
          </div>
          <div class="sign_in_modal sign_modal_content">
            <h2>ログイン</h2>
            <form class="new_user" action ="/users/sign_in" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="oHLlAj0JDR0syLFJq8pvBZgP3Tf2VBOuOl5VCtX7PkCHoBYqWAzU0+4Jy9zYT3kVMvzGwQ1/TTBeud1NLIX/xA==">
              <div class="field">
                <label for="user_email">メールアドレス</label><br>
                <input autofocus="autofocus" autocomplete="email" type="email" value="" name="user[email]">
              </div>

              <div class="field">
                <label for="user_password">パスワード</label><br>
                <input autocomplete="current-password" type="password" name="user[password]">
              </div>

              <div class="field">
                <input name="user[remember_me]" type="hidden" value="0"><input type="checkbox" value="1" name="user[remember_me]">
                <label for="user_remember_me">Remember me</label>
              </div>

              <div class="actions">
                <input type="submit" name="commit" value="ログイン" data-disable-with="ログイン" class="btn btn-default">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/items/edit.html.erb
<div class="main">
	<div class="container-fluid">
		<div class="row">
			<h1 style="line-height: 3em">管理者　登録商品編集ページ</h1>
			<div class="col-md-2"></div>
			<div class="col-md-8">
				<%= form_for(@item) do |f| %>
					<p class="about-item" style="font-weight: bold;">商品画像</p>
					<div class="form-group">
					<%= f.attachment_field :image, class: 'form-control',placeholder: '画像を選択してください' %>
					</div>
					<p class="about-item" style="font-weight: bold;">商品名</p>
					<div class="form-group">
					<%= f.text_field :name, class: 'form-control',placeholder: '商品名を入力してください'  %>
					</div>
					<p class="about-item" style="font-weight: bold;">商品名</p>
					<div class="form-group">
					<%= f.text_area :caption, class: 'form-control',placeholder: '商品説明を入力してください'  %>
					</div>
					<button type="submit" class="btn btn-default">更新する</button>
			<% end %>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
</div>

app/views/items/index.html.erb
<div class="main">
	<div class="container-fluid">
		<div class="row">
			<% if user_signed_in? %>
				<% if current_user.admin == true %>
					<h1 style="line-height: 3em">登録商品一覧</h1>
				<% else %>
					<h1 style="line-height: 3em">Paperをご利用いただきありがとうございます。</h1>
					<p class="item-announce">毎月ご利用される商品を選択してください</p>
					<p class="item-announce">※選択してから1ヶ月以内は商品を変更できません。</p>
				<% end %>
			<% end %>

			<% @items.each do |item| %>
				<div class="col-md-4">
					<%= attachment_image_tag item, :image, :size => "300x300" %>
					<p class="about-item" style="font-weight: bold;">商品名</p>
					<%= item.name %>
					<p class="about-item" style="font-weight: bold;">商品説明</p>
					<%= item.caption %>

					<% if current_user.select.present? %>
						<% if current_user.select.created_at < Time.current.ago(1.month) %>
							<div class="select-form">
								<%= form_tag("/selects") do %>
								<!-- チェックボックスを用いて、selectの配列に、item_idと0.1を入れるようにする。 -->
								<%= check_box "select", "#{item.id}", class: "checkbox" %>
								<input type="submit" value="確定">
								<% end %>
							</div>
						<% else %>
						<!-- チェックボックス表示させない -->
						<p style="line-height: 3em" >※ご注文から30日間は商品変更できません</p>
						<% end %>
					<% else %>
						<div class="select-form">
							<%= form_tag("/selects") do %>
							<!-- チェックボックスを用いて、selectの配列に、item_idと0.1を入れるようにする。 -->
							<%= check_box "select", "#{item.id}", class: "checkbox" %>
							<input type="submit" value="確定">
							<% end %>
						</div>
					<% end %>
					<% if user_signed_in? %>
						<% if current_user.admin == true %>
							<%= link_to "Show", item_path(item.id) %>
						<% end %>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/items/new.html.erb
<div class="main">
	<div class="container-fluid">
		<div class="row">
			<h1 style="line-height: 3em">管理者 新商品投稿ページ</h1>
			<div class="col-md-2"></div>
			<div class="col-md-8">
				<%= form_for(@item) do |f| %>
				<p class="about-item">商品画像</p>
				<div class="form-group">
				<%= f.attachment_field :image, class: 'form-control',placeholder: '画像を選択してください' %>
				</div>
				<p class="about-item">商品名</p>
				<div class="form-group">
				<%= f.text_field :name, class: 'form-control',placeholder: '商品名を入力してください' %>
				</div>
				<div class="form-group">
				<p class="about-item">商品説明</p>
				<%= f.text_area :caption, class: 'form-control',placeholder: '商品説明を入力してください' %>
				</div>
				<button type="submit" class="btn btn-default">出品する</button>
				<% end %>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
</div>

app/views/items/show.html.erb
<div class="main">
	<div class="container-fluid">
		<div class="row">
			<h1 style="line-height: 3em">管理者　商品詳細ページ</h1>
			<div class="col-md-2"></div>
			<div class="col-md-8">
				<p class="about-item" style="font-weight: bold;">商品画像</p>
				<%= attachment_image_tag @item, :image, :size => "300x300" %>
				<p class="about-item" style="font-weight: bold;">商品名</p>
				<%= @item.name %>
				<p class="about-item" style="font-weight: bold;">商品説明</p>
				<%= @item.caption %>

				<%= link_to "商品を編集する", edit_item_path(@item.id) %>
				<%= link_to "商品を削除する", item_path(@item.id), method: :delete, "data-confirm"=> "こちらの商品を本当に削除しますか?" %>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
  </head>

  <body>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample7">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"></a>
          </div>
          <div class="collapse navbar-collapse" id="navbarEexample7">
            <ul class="nav navbar-nav">
              <li><a class="header-logo">Paper</a></li>
            </ul>
            <p class="navbar-text navbar-right">
              <% if user_signed_in? %>
                <% if current_user.admin == true %>
                  <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to " 商品一覧", items_path %></li>
                    <li><%= link_to " 商品登録", new_item_path %></li>
                    <li><%= link_to " 顧客情報一覧", users_path %></li>
                    <li><%= link_to " 注文一覧", selects_path %></li>
                    <li><%= link_to " ログアウト", destroy_user_session_path, method: :delete %></li>
                  </ul>
                <% elsif current_user.select.blank? %>
                  <ul class="nav navbar-nav navbar-right">
                <!-- ログインしたばかりの新規のお客様はヘッダーなし -->
                    <li><%= link_to " ログアウト", destroy_user_session_path, method: :delete %></li>
                  </ul>
                <% else %>
                  <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to " 商品一覧/変更", items_path %></li>
                    <li><%= link_to " マイページ", user_path(current_user.id) %></li>
                    <li><%= link_to " ログアウト", destroy_user_session_path, method: :delete %></li>
                  </ul>
                <% end %>
              <% else %>
                  <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to " Home", root_path %></li>
                    <li><%= link_to " About", about_path %></li>
                  </ul>
              <% end %>
            </p>
          </div>
        </div>
      </nav>
    </div>
    <% if flash[:notice] %>
      <div class="alert alert-warning">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>

    <footer></footer>
  </body>
</html>

app/views/select/index.html.erb
<div class="main">
	<div class="container-fluid">
		<div class="row">
			<h1 style="line-height: 4em">注文履歴一覧</h1>
			<h2>商品名検索</h2>
			  <%= form_tag(selects_path,:method => 'get') do %>
			  <!-- 下記は入ってきた文字をパラメーターに代入する -->
			  <%= text_field_tag :search %>
			  <%= submit_tag 'Search' %>
			<% end %>

			<div class="table-responsive">
				<% @selects.each do |select| %>
					<table class="table table-striped" style="table-layout:fixed;">
						<thead>
							<tr>
								<th>選択商品</th>
								<th>商品名</th>
								<th>Email</th>
								<th>郵便番号</th>
								<th>住所</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><%= attachment_image_tag select.item, :image, :fill, 100, 100, format: 'png' %></td>
								<td><%= select.item.name %></td>
								<td><%= select.user.email %></td>
								<td><%= select.user.zip_code %></td>
								<td><%= select.user.home_address %></td>
							</tr>
						</tbody>
					</table>
				<% end %>
				<%= paginate @selects, class: "paginate" %>
			</div>
		</div>
	</div>
</div>

app/views/select/show.html.erb
<div class="main">
	<div class="container-fluid">
		<div class="row">
			<h1 style="line-height: 3em">ご注文いただきありがとうございます。</h1>
			<h1>こちらの商品が毎月届きます。</h1>
			<div class="col-md-2"></div>
			<div class="col-md-8">
			<h2 class="sub-title">選択中の商品</h2>
				<div class="item_images">
				<%= attachment_image_tag @select.item, :image, :fill, 200, 200 %>
				</div>
			<table>
				  <tr>
				    <th>商品名</th>
				    <td><%= @select.item.name %></td>
				  </tr>
				  <tr>
				    <th>商品説明</th>
				    <td><%= @select.item.caption %></td>
				  </tr>
			</table>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
</div>

<div class="main">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
			<h2 class="sub-title">お届け先情報</h2>
			<table>
			  <tr>
			    <th>郵便番号</th>
			    <td><%= @select.user.zip_code %></td>
			  </tr>
			  <tr>
			    <th>住所</th>
			    <td><%= @select.user.home_address %></td>
			  </tr>
			</table>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="main">
	<div class="container-fluid">
		<div class="row">
			<h1 style="line-height: 3em">お客様情報編集画面</h1>
			<div class="col-md-2"></div>
			<div class="col-md-8">
			<%= form_for(@user) do |f| %>
				<p>郵便番号</p>
				<div class="form-group">
				<%= f.text_field :zip_code, class: 'form-control',placeholder: '郵便番号を入力してください' %>
				</div>
				<p>お届け先住所</p>
				<div class="form-group">
				<%= f.text_field :home_address, class: 'form-control',placeholder: '住所を入力してください' %>
				</div>
				<button type="submit" class="btn btn-default">お届け先情報更新</button>
			<% end %>

			<%= link_to "サービスを退会する", user_path(@user.id), method: :delete, "data-confirm"=> "本当に退会されますか？" %>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="main">
	<div class="container-fluid">
		<div class="row">
			<h1 style="line-height: 3em">サービス利用者一覧</h1>
			<h2>住所検索</h2>
			  <%= form_tag(users_path,:method => 'get') do %>
			  <%= text_field_tag :search %>
			  <%= submit_tag 'Search', :name => nil %>
			<% end %>
			<div class="table-responsive">
					<table class="table table-striped" style="table-layout:fixed;">
						<thead>
							<tr>
								<th>Email</th>
								<th>郵便番号</th>
								<th>住所</th>
							</tr>
						</thead>
						<% @users.each do |user| %>
						<tbody>
							<tr>
								<td><%= link_to user.email, user_path(user.id) %></td>
								<td><%= user.zip_code %></td>
								<td><%= user.home_address %></td>
							</tr>
						</tbody>
						<% end %>
					</table>
				<%= paginate @users, class: "paginate" %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="main">
	<div class="container-fluid">
		<div class="row">
			<h1 style="line-height: 3em">マイページ</h1>
			<div class="col-md-2"></div>
			<div class="col-md-8">
			<h2 class="sub-title">毎月お届けする商品</h2>
				<% if @user.select.blank? %>
					<p>現在、商品が選択されていません。</p>
					<%= link_to "商品を選択する", items_path%>
				<% else %>
				<div class="item_images">
					<%= attachment_image_tag @user.select.item, :image, :fill, 200, 200, format: 'png' %>
				</div>
				<table>
					  <tr>
					    <th>商品名</th>
					    <td><%= @user.select.item.name %></td>
					  </tr>
					  <tr>
					    <th>商品説明</th>
					    <td><%= @user.select.item.caption %></td>
					  </tr>
					  <tr>
					    <th></th>
					    <td><%= link_to '選択商品変更' , items_path %></td>
					  </tr>
				</table>
				<% end %>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
</div>

<div class="main">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
			<h2 class="sub-title">お客様情報</h2>
			<table>
			  <tr>
			    <th>郵便番号</th>
			    <td><%= @user.zip_code %></td>
			  </tr>
			  <tr>
			    <th>住所</th>
			    <td><%= @user.home_address %></td>
			  </tr>
			  <tr>
			    <th></th>
			    <td><%= link_to 'お届け先情報変更' , edit_user_path(@user.id) %></td>
			  </tr>
			</table>
			</div>
			<div class="col-md-2"></div>
		</div>
	</div>
</div>